name: Build + Test + Deploy if main 

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
        
      - name: Setup dotnet 6+7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.x
            7.x
            
      - name: Build and test
        run: |
            dotnet build
            dotnet test
  
  deploy_if_main_branch:
    runs-on: ubuntu-latest
    needs: test
    
    if: github.ref == 'refs/heads/master'
    steps:
      
      - uses: actions/checkout@v3
      
      - name: Build and package with release configuration
        run: |
          dotnet build -c Release
          dotnet publish -c Release -o Publish/Package
        
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Deploy package to Azure Function
        uses: Azure/functions-action@v1.4.8
        with:
          app-name: TestProject
          package: Publish/Package
