name: Build + Test + Deploy if main 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
        
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Execute Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: gradle-project

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: github/upload-artifact@v2
          path: artifacts

      - name: Archive test report
        uses: action/upload-artifact@v2 
        with:
          name: Test report
          path: build/reports/tests/test 
              
            
  
  deploy_if_main_branch:
    runs-on: ubuntu-latest
    needs: test
    
    if: github.ref == 'refs/heads/master'
    steps:
      
      - uses: actions/checkout@v3
              
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          app-name: gradle-project
          package: build/libs/Package

      - name: Deploy package to Azure Function
        uses: Azure/functions-action@v1.4.8
        with:
          app-name: TestProject
          package: build/libs/Package
