name: Build + Test + Deploy if main 

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
        
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: gradle         
      - name: Build with gradle
        run: ./gradlew build 
              
            
  
  deploy_if_main_branch:
    runs-on: ubuntu-latest
    needs: test
    
    if: github.ref == 'refs/heads/master'
    steps:
      
      - uses: actions/checkout@v3
              
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      
      - name: Download a single artifact
        uses: actions/download-artifact@v3

      - name: Deploy package to Azure Function
        uses: Azure/functions-action@v1.4.8
        with:
          app-name: TestProject
          package: build/libs/Package
