name: Build + Test + Deploy if main 

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
        
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: my.project
            
  
  deploy_if_main_branch:
    runs-on: ubuntu-latest
    needs: test
    
    if: github.ref == 'refs/heads/master'
    steps:
      
      - uses: actions/checkout@v3
      
      - name: Build and package with release configuration
        run: |
          dotnet build -c Release
          dotnet publish -c Release -o Publish/Package
        
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Deploy package to Azure Function
        uses: Azure/functions-action@v1.4.8
        with:
          app-name: TestProject
          package: Publish/Package
